# Section 1: Numpy 소개
## Section 2.1 : ndarray 생성

- array 함수를 사용하여 배열 생성하기

In [3]:
import numpy as np

In [4]:
### ndarray 생성
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

- zeros, ones, empty 함수를 사용하여 배열 생성하기

In [5]:
## zeros, ones, empty 함수를 사용한 배열생성
print(np.zeros((3,3)))
print(np.ones((2,2)))
print(np.empty((4,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[4.67296746e-307 1.69121096e-306 8.90071985e-308 8.34441742e-308]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 1.15706896e-306 1.33512173e-306 8.34402698e-308]]


- arrange 함수를 사용하여 배열 생성하기

In [6]:
## arange 함수를 사용한 배열 생성하기
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Section2.2 : ndarray 배열의 모양, 차수, 데이터 타입 확인

- Shape, ndim, dtype 함수를 사용항 모양, 차수, 데이터 타입 확인하기

In [9]:
## shape, ndim, dtype 함수를 사용한 모양 차원 데이터 타입 확인
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("*"*10)
print(arr.shape)
print("*"*10)
print(arr.ndim)
print("*"*10)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
**********
(2, 3)
**********
2
**********
int32


## Section 2.3 : ndarray 배열의 타입변환

- astype 함수를 사용하여 정수형 데이터 배열을 실수형 데이터 배열로 변환하기

In [10]:
## astype 함수를 사용한 데이터 타입 변환
arr_int = np.array([1,2,3,4])
arr_int.dtype

dtype('int32')

In [11]:
arr_float = arr_int.astype(np.float64)
arr_float.dtype

dtype('float64')

- 문자형 데이터 배열을 정수형 데이터 배열로 변환하기

In [12]:
## 문자형 데이터 배열을 정수형 데이터배열로 변환
arr_str = np.array(['1', '2', '3'])
arr_str.dtype

dtype('<U1')

In [13]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

## Section 2.4 : ndarray 배열의 연산

- 기본 연산자와 함수를 통해 벼열 연산한기

In [15]:
## 배열 연산
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [16]:
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


- dot 함수를 사용하여 행렬의 곱 계산하기

In [18]:
## dot함수를 사용한 행렬의 곱 계산
print(arr1.dot(arr2))
print(np.dot(arr1,arr2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Section 2.5 : ndarray 배열 슬라이싱 하기

- ndarray 배열 슬라이싱 하기

In [19]:
## 배열 슬라이싱
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_1 = arr[:2, 1:3]
arr_1

array([[2, 3],
       [5, 6]])

- ndarray 정수 배열 인덱싱 하기

In [20]:
## 정수 배열 인덱싱
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,2])
print(arr[[0,1,2],[2,0,1]])

3
[3 4 8]


- Boolean  배열 인덱싱하기

In [21]:
##Boolean 배열 인덱싱
arr = np.array([[1,2,3],[4,5,6]])
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]]


In [22]:
print(arr[idx])

[4 5 6]


## Section 3.1 : Wine Quality 데이터 설명

- WIne Quality 데이터에는 포르투갈의 레드와인과 화이트 와인 두개의 데이터 셋이 있다. 가각의 데이터 셋안에는 물리 화학적 실험에 대한 12개의 변수들이 있다.

## Section 3.2 : Wine Quality 데이터 불러오기

- 실습은 Wine Quality 데이터(red, white) 중 winequality-red.csv파일 만을 사용한다.

In [24]:
import numpy as np

In [26]:
## winequality-red.csv 파일 불러오기
redwine = np.loadtxt(fname = './winequality-red.csv',
                    delimiter = ';', skiprows = 1)

redwine

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

## Section 3.3 : Wine Quality 데이터를 활용한 기초 통계 분석

- Numpy에는 기본적인 배열 통계 메서드가 있다. sum, mean과 같은 기본적인 통계 메서드를 통해 3.2에서 불러온 redwine 데이터의 기초적인 통계분석을 해본다.

In [27]:
### redwine 데이터셋의 합(sum)
print(redwine.sum())
### redwine 데이터셋의 평균(mean)
print(redwine.mean())
print(redwine.mean(axis = 0))
print(redwine[:,0].mean())

152084.78194
7.926036165311652
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]
8.31963727329581


In [28]:
## redwine 데이터셋의 최대값(max)
print(redwine.max(axis = 0))
## redwine 데이터셋의 최솟값(min)
print(redwine.min(axis = 0))

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
